# Generated by Django 3.2.7 on 2021-09-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.IntegerField()),
                ('c', models.CharField(max_length=255)),
                ('d', models.DateField()),
                ('dt', models.DateTimeField()),
            ],
        ),
    ]
